version: '3'
services:
  redis:
    image: redis
    container_name: redis
    ports:
    - 6379:6379
    restart: always
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"

  websocket-server-service:
    build: websocket-server-service
    image: withme3.0/websocket-server-service
    restart: always
    depends_on:
      - redis
    ports:
    - 21002:8282
    networks:
    - withme-network

  user-service:
    build: user-service
    image: withme3.0/user-service
    restart: always
    ports:
    - 21003:8081
    networks:
    - withme-network


networks:
  withme-network:
    driver: bridge